on:
  push:
    branches:
      - develop

name: Verify nix-shell config
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Enter nix-shell
      run: nix-shell --pure

    - name: Generate lockfile
      run: cargo generate-lockfile

    - name: Cache cargo registry and build outputs
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}

    - name: Run cargo check
      run: cargo check
